#!/bin/sh

# Make file for FreeJ2ME Libretro
all: freej2me_libretro.c
	@echo "Building FreeJ2ME libretro core ..."
	@gcc freej2me_libretro.c -o freej2me_libretro.so

clean:
	rm ./freej2me_libretro.so
